// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqblrUQ0cq98ZxExDJR9Zpxthm-gsPtDM',
    appId: '1:432662656532:web:d7d8c46130e5347e9c1901',
    messagingSenderId: '432662656532',
    projectId: 'tudushka-dev',
    authDomain: 'tudushka-dev.firebaseapp.com',
    storageBucket: 'tudushka-dev.appspot.com',
    measurementId: 'G-4FXCC2W399',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQQudnmcxvcl3QmLvdwUXtBa3RzqQMpQg',
    appId: '1:432662656532:android:32ebb070146904af9c1901',
    messagingSenderId: '432662656532',
    projectId: 'tudushka-dev',
    storageBucket: 'tudushka-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-HhXMn5o-9rahYulbXnkuKioTkzqtldU',
    appId: '1:432662656532:ios:b0cbce0d85562cfd9c1901',
    messagingSenderId: '432662656532',
    projectId: 'tudushka-dev',
    storageBucket: 'tudushka-dev.appspot.com',
    iosClientId: '432662656532-jhibrmd0cn5egnsgfvg10b1ort0l45a5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tudushka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-HhXMn5o-9rahYulbXnkuKioTkzqtldU',
    appId: '1:432662656532:ios:2d3dac4e9a2d4fde9c1901',
    messagingSenderId: '432662656532',
    projectId: 'tudushka-dev',
    storageBucket: 'tudushka-dev.appspot.com',
    iosClientId: '432662656532-m0pec7a51c0bl5cmjsdgaheooisoierk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tudushka.RunnerTests',
  );
}
